### ISSUE TITLE
Nether lamp posts break through bedrock roof in the nether

### ISSUE THREAD

**Issue by KatouMegumi-osu** [frqnny/mostructures#11]
Mod version is mostructures-1.0.0-pre3+mc.1.16.2.jar
![javaw_5MCVG3AYxb](https://user-images.githubusercontent.com/30472780/94347015-357e9480-004a-11eb-8349-af1037ff1663.png)

**Comment by frqnny** [comment]
Fixed in 1.0.0 (Coming out soon!)
