### ISSUE TITLE
Boulders spawn constantly in certain biomes

### ISSUE THREAD

**Issue by magneticflux-** [frqnny/mostructures#12]
In `minecraft:giant_tree_taiga_hills`, boulders cover the landscape entirely. They do not appear anywhere else.

This is with the `boulder_chance` "frequency" option set to 1-in-100000 chunks:
![image](https://user-images.githubusercontent.com/9124288/96410918-49cb3280-11ad-11eb-936a-337914e71e41.png)

**Comment by frqnny** [comment]
I don't think those are mine. 

Edit:

As seen below, It is Repurposed Structures. Link to their github: https://github.com/TelepathicGrunt/RepurposedStructures-Fabric

**Comment by TelepathicGrunt** [comment]
@magneticflux- Those are boulders from my mod called Repurposed Structures. You can configured or removed them with my mod's config

**Comment by magneticflux-** [comment]
Sorry for the confusion, I didn't realize both mods added boulders!
