### ISSUE TITLE
An unknown Mo Structure's structure has a typo in a jigsaw block or something.

### ISSUE THREAD

**Issue by TelepathicGrunt** [frqnny/mostructures#14]
I ported Blame to fabric and ran it on AoF3 to see what issues have been going around. I found this popped up in the logs. Basically, one of Mo' Structure's structure has `minecraft:mostructuresvillager/villager` instead of `minecraft:mostructures/villager/villager` in their jigsaw blocks or something but I do not know which structure it is. I can experiment later to try and narrow it down.

![image](https://user-images.githubusercontent.com/40846040/99613213-27fbe000-29e5-11eb-83d9-36f207158e5f.png)

**Comment by TelepathicGrunt** [comment]
Also below that is `[21:13:48] [Worker-Main-23/WARN]: Empty or none existent pool: minecraft:village/desert/street` which might be part of the same structure. I was in a desert at the time. If this is part of the same Mo Structure, then this pool name is also a typo as it should be `minecraft:village/desert/streets` so hopefully with these typos fixed, your structure will spawn more complete now!

Edit: more pool errors are in the logs. I'll list them here:
`[21:16:08] [Worker-Main-14/WARN]: Empty or none existent pool: mostructures:villager/market`
`[21:16:00] [Worker-Main-8/WARN]: Empty or none existent pool: mostructures:abandoned/village/churches`

**Comment by TelepathicGrunt** [comment]
I went and improved Blame to actually give more info on what piece has the typo in the jigsaw blocks and so far, I could only find the villager feature and market errors. The `minecraft:village/desert/streets` must had been another mod so ignore that lol. 

Here's the extra info!
![image](https://user-images.githubusercontent.com/40846040/99881140-d8383700-2be5-11eb-8a06-cf0481b14099.png)

**Comment by frqnny** [comment]
Semi-fixed in 1.0.0. It doesn't really do anything now, only thing that remains is it trying to load a block entity from air, but that doesn't really seem to be a world-breaking issue preventing me from releasing a new version.
