### ISSUE TITLE
Possible Bug With Modded Biomes

### ISSUE THREAD

**Issue by TheBrokenRail** [frqnny/mostructures#2]
This (https://github.com/franiscoder/mostructures/blob/1.16.x/src/main/java/io/github/franiscoder/mostructures/common/init/ModStructures.java#L39) should probably be a mixin to ```DefaultBiomeFeatures``` because otherwise modded biomes won't get the feature which will cause it to be cut off on biome borders with modded biomes, make sure you only add the ```StructureFeature``` to the correct biomes though.

**Comment by frqnny** [comment]
I think a registry callback event will be better but I'll look into it, thank you!

**Comment by frqnny** [comment]
Psst, I think you might be wrong about this, Half told me that Registry.BIOME covers all of it, but thank you, I'll keep this open for a response and close it in a week.

**Comment by TheBrokenRail** [comment]
The issue comes when a mod initializes after yours changing ```Registry.BIOME```.

**Comment by frqnny** [comment]
Yeah, Grunt told me you are right, so I will fix this soon, thank you.

**Comment by frqnny** [comment]
fixed when 0.1.0 comes out
