### ISSUE TITLE
Can't Find Any Castles in the Sky

### ISSUE THREAD

**Issue by AllisonMetzger** [frqnny/mostructures#21]
I've spent some time teleporting around several minecraft worlds using this mod, and I've yet to find a castle in the sky. I'm using the /locate command, and always get "could not find that structure near by", despite teleporting 10,000+ blocks away at a time and reusing the command. Is there a certain biome it generates in, or am I missing something? No issue using /locate for any other structures added by this mod.

**Comment by frqnny** [comment]
Can you tell me what version you are using, of both MC and Mo Structures?

**Comment by K0-RR** [comment]
Weird, for me they generate.

**Comment by frqnny** [comment]
Closing this, no response.
