### ISSUE TITLE
Are you taking suggestions for more structures?

### ISSUE THREAD

**Issue by K0-RR** [frqnny/mostructures#25]
I have some images (but with higher res than this one).
This could be a shrine, maybe with an enchanting table in the middle or a destroyed nether portal.
![image](https://user-images.githubusercontent.com/43277609/110220475-3bfd1c00-7ec6-11eb-8095-4a225e65c065.png)

**Comment by frqnny** [comment]
Interesting! This looks cool. And yes, I am taking structure suggestions.

If you want me to add this structure, just pass me either the world OR the structure nbt. That way i can just edit it and get it in the mod as fast as possible. TBH, this structure could spawn somewhere in the jungle. Good job! I only think it could be a tiny bit smaller so the size is rational to things like the Jungle Pyramid.

**Comment by K0-RR** [comment]
I will try to send screenshots with other structures and the world file tomorrow if I will have time for it. Can I ask how long it could take you to implement it?

**Comment by frqnny** [comment]
Probably just an hour. But if you're asking when I will do it, it'll probably be a few days since I'm busy. And when I will release it is another matter, because I would also have to get through lots of new ideas I am planning.

**Comment by K0-RR** [comment]
What about some abandoned houses? There are no traces of "human" activity in this game. Isn't it weird I'm the only steve-like creature?
![image](https://user-images.githubusercontent.com/43277609/110239604-216b8700-7f48-11eb-9f5c-736972268f2e.png)
![image](https://user-images.githubusercontent.com/43277609/110239608-28929500-7f48-11eb-871e-4745d2107964.png)

**Comment by K0-RR** [comment]
I mean if there are temples and more importantly ruined portals then who build them? Don't tell me that villagers.

**Comment by frqnny** [comment]
Thats really the mystery. Instead of actually creating lore about it, it’s up to the users interpretation. Anyway houses might be a little too much... i’ll see what i can think of bc i still want to work on my other mods

**Comment by K0-RR** [comment]
I'm sure you are familiar with battle towers mods like this one. The reason I'm requesting this to you instead of using one of these mods is that all battle towers mods aren't vanilla clients friendly - they add this golem boss which means the mod can't be server-only. What do you think about it?
![image](https://user-images.githubusercontent.com/43277609/110242796-ec673080-7f57-11eb-80a4-8c8d08d72b65.png)

**Comment by frqnny** [comment]
To be honest, battle towers are their own genre of structure mods, and they do normally require client-sided stuff to be able to provide the best experience. However, the idea of developing dungeons themselves doesnt sound too bad. Maybe I can try to make a dungeon or some undeground structure.  thatll wait until i 1.17, probably due to new cave/ mountain system

**Comment by K0-RR** [comment]
> I only think it could be a tiny bit smaller

I will try to make it 19x19 (main size 11x11) instead of 20x20 (12x12). I just realized that in vanilla I can't place torches on slabs wtf Mojang...

**Comment by frqnny** [comment]
Oh wait! Normally Mo Structures likes to either make 16x16 or 32x32 structures so it fits in chunks better, and generally that also makes generation a little better. 16x16 please!

**Comment by K0-RR** [comment]
I was looking for some inspiration and found this
![image](https://user-images.githubusercontent.com/43277609/110671268-9c45d380-81ce-11eb-9770-5e68cec35914.png)
Could be 32x32 or bigger, what do you think about it?

**Comment by frqnny** [comment]
The funny thing about those meteor craters was that any exterior feature, like a lake or something, would just break it. So no, I don't want to do a meteor crater. I thought about it before but seeing how it turned out in other mods made me back off from the idea.

**Comment by HAMM3REXTREME** [comment]
I have some more suggestions for structures. Like this abandoned tree house:
![image](https://user-images.githubusercontent.com/80393733/110759189-5858da00-8273-11eb-83ed-06d4ca028496.png)
World Download: [StructureTreeHouse.zip](https://github.com/frqnny/mostructures/files/6121631/StructureTreeHouse.zip)

**Comment by frqnny** [comment]
I generally try to have a "human" feel of structures, and I don't think a giant tree will fit into the mod, specially one that size. Maybe I can try to build one for a later update, but idk. :P

**Comment by Hyperbean18** [comment]
I tried commenting this on cf a while back, but it got marked as spam. Anyway, here it is:

In the vein of the pillager factory, why not add a structure called the piglin barracks? It could consist of dorms, a dining hall/kitchen, a training arena, a weapons storage area, a central office, secret basement etc. 

They could be added either as rooms in a large building (like rooms in a stronghold), or as standalone buildings that collectively make up the larger structure (like in a village). 

There could be various posters around the structure in the form of banners. The instructors could be piglin brutes, and you could have some hoglins caged up as practice dummies for the students. 

Just a couple ideas, hopefully you can figure something out

**Comment by frqnny** [comment]
I'ma close this but I do want to do something like Piglin Barracks.
