### ISSUE TITLE
no Rabbit loot

### ISSUE THREAD

**Issue by Deltalius** [frqnny/mostructures#30]
in the 1.1.0 version of mostructures rabbits dont trop any loot or exp

**Comment by frqnny** [comment]
Oh really? Can you try to reproduce it again? What are u on, latest snapshot or 1.16.5? Im pretty sure they do.

**Comment by Deltalius** [comment]
i am using 1.16.5 with fabric api 0.32.0 and mostructures 1.1.0

**Comment by frqnny** [comment]
Mate, IDK what ur on about. I just killed the Killer Bunny Rabbit and it worked for me. 
Can you try to reproduce the issue?

**Comment by Deltalius** [comment]
the Killer Bunny Rabbit drops loot for me to but normal passiv Rabbits drop nothing

**Comment by frqnny** [comment]
I realize where the bug is. I apoligize.

**Comment by frqnny** [comment]
This is now fixed in dev. However it iwll be a long while before I release Mo' Structures 1.2.0.
