### ISSUE TITLE
Lore (?)

### ISSUE THREAD

**Issue by Striker686** [frqnny/mostructures#34]
I know this isnt an issue, but im still interested in the "lore" of this mod/minecraft world.

1. I found a total of 4 written books in all structures. 

First one in abandoned church with phrases "hey", "how u doing" and then some weird numbers, probably a clue.

Second one in pillager factory, that contained a list of thing of someones inventory, shimpents, raids and "next raid: ?????????".

Third one in big pyramid. This was the biggest one. It was a guide on how to transfer skeleton skulls to wither skeleton skulls,
with some words impossible to read + statement from someone who tried the experiment, saying it destroyed his entire village
and that no one should make it or s̷̰͎̤̹̦̘̠̬̎̐͑͂̎͘͝ͅǫ̶̨̧͙̥̝̱͈̲͓̌̓m̴͕̖̰̭̪̬̥̍̀͌̎̿͑͆̄̕͜͜͝͠e̶̙̖̮̫̞̅̋̓́͗̏͝t̸̢̘͕̳̮͓̞̹͍̻̳́͗͌̓͛͌͜͜ͅh̶̩̠̜͔̙̞͙͎̻́̓̑̆̊͌̃͋̉̚̕͠͝͠͝ī̵̡̖̘͍̒͆͑n̵̡̰̲͕̤͍̤̘̺̈́̍̈̓̉̇̌͑̅͑̀ͅg̵̬͔͚̳̊̂̓̎̾̚͝ ̸̢̞̝͔̃̓͋̆̏̃̃͑̃̚w̶̘͉̱̦̼͔̋͐͆̌̈́̊͛̽͘̕͝i̶̪̩̞̐͊͐͑͆̐́̽͝l̷̤̱͔͙̑͂̃̑̇̓̆͂̔͋̓̏̃͝͠l̵̩͓̮̪͛͗̽̈̌̀̍̂͆͒̂̈̋̅̈ļ̵̭̿̊̅̔̐͊̍̒̅ ̶̧̨̡̼̖̞̭̺̩͍̖̙͖̙̌̔̇̈́͊̈́̂́̊͌͝h̷̗̹̑̽̓̎͗̇̈͌͌̔͝͝͠ạ̵̧̔͑̆͗̒̆͗̓́̀̉́̂̆͆p̸̨̖͎̹̺̥͆̃͝ͅp̶͕̘̞̥̻̪͔̈́̂̈́̑̎̅ë̶̯̄̓́̋͂́̚ñ̶̮͙̼̏͆̃̈̉́̃͑͘͠ ̴̨̬̾̈́͛͑̿̍͝͠i̵̮̞͑̑͂̑̆̾͂̈ͅḏ̸̖̹͓͎͔͇͖͈̜́͊̎̎̊̑̚k̶̨̨̯͍͎͕̩̹̩̺̩̯̲̾͗͆̑̀̂̕̚͜͝.

The fourth one was the weirdest. It was in villager market saying "the end."

Im sorry for wasting your time with this terrible post, but i hope someone knows more about this than me.

**Comment by frqnny** [comment]
/shrug you write your own world lore :)
