### ISSUE TITLE
Add mobs spawning to structures

### ISSUE THREAD

**Issue by NixityNull** [frqnny/mostructures#35]
This is more of a pet peeve than an actual issue, but could you add some sort of mobs spawning near or in some of the structures by default, like pillagers in normal Minecraft's mansions? They just seem empty without someone there, and the lack of obstacles inside the structures kind of just turns it into "here, have a prebuilt base" that makes even villages look balanced.

Specific suggestions include
-Villagers in some of the house structures like the tavern and barn and the  because just having empty houses is essentially just handing the player a free home
-strays or other hostiles near the ice tower to make it more of a challenge to turn into a base
-Villagers/pillagers for hot air balloons because it makes no sense for there to be a working hot air balloon floating around with NOBODY INSIDE.

I will let you know if I find any other structures that fit this list.

**Comment by frqnny** [comment]
Sure! I'll see about that. Ice tower does have strays spawning, but I can try to increase it.
