### ISSUE TITLE
Villager Market place and some abandoned farms cause game to crash.

### ISSUE THREAD

**Issue by Fade-Alchemist** [frqnny/mostructures#38]
I can confirm this is still a problem, I had to disable the Market- It loads in glitched, and if you approach the game will crash. The same happens with some variants of the abandoned farm as well.
https://github.com/frqnny/mostructures/issues/33#issuecomment-857441377

**Comment by Fade-Alchemist** [comment]
https://github.com/frqnny/mostructures/issues/33#issuecomment-857441377

**Comment by frqnny** [comment]
This looks like a Sodium crash. report there.

**Comment by Fade-Alchemist** [comment]
Thanks! Will do :D
