### ISSUE TITLE
Generation

### ISSUE THREAD

**Issue by C0DEHADES** [frqnny/mostructures#39]
So I have a server, and was wondering if structures are not generated if you add the mod later. I've been roaming around a tundra, and haven't seen anything. I added the mod not so long after we started it, and I'm not sure if is not working or we just haven't found a single one.

**Comment by frqnny** [comment]
Try using /locate to see if it returns anything. If it does, it might be that the structures are just rare. (We don’t add much to tundras anyway)
Ill put this for 1.2.1 for rebalancing

**Comment by FwuffyPetsOwO** [comment]
yes, Structures (any worldgen) will not affect already loaded chunks because they've already been loaded. Try exploring out where you haven't gone yet, you should be able to find them.

**Comment by frqnny** [comment]
Rereading this, yeah it doesn't regenerate where structures should be. Only during newly generated chunks.

**Comment by C0DEHADES** [comment]
> Rereading this, yeah it doesn't regenerate where structures should be. Only during newly generated chunks.

OK It does work, but the pillager factory I found almost didn't generate pillager. I only found 2 pillagers inside, and I don't know if it's not supposed to happen.

**Comment by frqnny** [comment]
That's just minecraft being weird, i can't help with that. youre fine.
