### ISSUE TITLE
Incompatible with Wythers Overhauled Overworld

### ISSUE THREAD

**Issue by ConqAra** [frqnny/mostructures#40]
For some reason any structures from mo'structures will NOT spawn if you are using the "Oh The Biome's You'll Go" Mod.

Mod: https://www.curseforge.com/minecraft/mc-mods/oh-the-biomes-youll-go-fabric

**Comment by frqnny** [comment]
it works in AOF pack, idk what you mean. what mc versiom, 1.16.5?

**Comment by ConqAra** [comment]
yeah its 1.16.5, for me they literally do not spawn when using BYG
very weird. I tried to /locate on every structure and could not find a single one, even after making numerous worlds

**Comment by frqnny** [comment]
show me latest.log after you create a world, try to /locate them

**Comment by ConqAra** [comment]
I'm also using this mod for improved generation on default biomes, which mo'structures works on. But If I add BYG to the mix, it won't generate any structures from your mod. 

https://www.curseforge.com/minecraft/mc-mods/william-wythers-overhauled-overworld

**Comment by ConqAra** [comment]
Actually I don't think its byg, here is a log without the mod. I'm going to send another log afterwards with it.

Log: https://pastebin.com/ULbFbhqz

**Comment by ConqAra** [comment]
I'm thinking it's better end, now that i see it.

**Comment by frqnny** [comment]
Might be the wythers mod. I don't do anything that might do it but I will leave this incase it is me. Do a bug report on wythers.

**Comment by ConqAra** [comment]
here's another log just in case: https://pastebin.com/DQW4Mpg5

**Comment by ConqAra** [comment]
Apparently repurposed structures works with the Wythers mod, but your mod doesn't. Do you think it's a problem with Wyther's preventing unknown structure generation (mo'structures) specifically, or is it on your side?

**Comment by ConqAra** [comment]
ALSO very weird thing that might be important:  the balloons from mo'structures were still generating in the air, just no generation for anything else.

**Comment by frqnny** [comment]
I think I know the issue. It’s on Fabric API I believe. Maybe, Ill have to test.

**Comment by frqnny** [comment]
Turns out to be a bug with Fabric API. I PR'd a fix to 1.17, I'll see to when it gets backported to 1.16.5.

**Comment by frqnny** [comment]
Hey Conq! Can you try updating Fabric API?

**Comment by ConqAra** [comment]
POG it works, nice!
