### ISSUE TITLE
no market?

### ISSUE THREAD

**Issue by GabiArzu** [frqnny/mostructures#41]
I am using the mod (which is great btw) but i cant find any vanilla villages, and i tried locating the villager market but there are non at the locations im teleporting to... 

is it a bug or am i wrong about something?

**Comment by frqnny** [comment]
What version? Show me latest.log

**Comment by GabiArzu** [comment]
sorry i forgot to reply, the issue was not your mod but the dimensional doors mod.
thank you anyway!
