### ISSUE TITLE
Been having this on every launch while preparing spawn for the past week or so

### ISSUE THREAD

**Issue by AchalS-iglu** [frqnny/mostructures#42]
Doesn't crash or cause any issues but anyways

`****************** Blame Report 1.17-4.0.0-fabric ******************

 Failed to load structure nbt file from : mostructures:empty
 The path represented by this is:  data/mostructures/structures/empty.nbt
 Most common cause is that there is a typo in this path to the nbt file.
 Please let the mod author know about this so they can double check to make sure the path is correct.
 A common mistake is putting the structure nbt file in the asset folder when it needs to go in data/structures folder.
  Stacktrace of where this NBT file is being called by: [java.base/java.lang.Thread.getStackTrace(Thread.java:1191), com.telepathicgrunt.blame.main.MissingNBTBlame.addMissingNbtDetails(MissingNBTBlame.java:56), net.minecraft.class_3485.handler$zpa000$addMissingnbtDetails2(class_3485.java:535), net.minecraft.class_3485.method_15094(class_3485.java:65), net.minecraft.class_3485.method_15091(class_3485.java:53), net.minecraft.class_3470.<init>(class_3470.java:59), io.github.frqnny.mostructures.structure.VolcanicVentStructure$Piece.<init>(VolcanicVentStructure.java:66), io.github.frqnny.mostructures.MoStructures$$Lambda$2065/0x00000000b6971500.load(Unknown Source), net.minecraft.class_3195.method_28660(class_3195.java:151), net.minecraft.class_2852.method_12392(MixinChunkSerializer.java:415), net.minecraft.class_2852.method_12395(MixinChunkSerializer.java:175), net.minecraft.class_3898.md6ebb3a$lambda$loadChunk$0$18(MixinThreadedAnvilChunkStorage.java:6275), net.minecraft.class_3898$$Lambda$6709/0x0000000084946238.apply(Unknown Source), java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:642), java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:478), org.threadly.concurrent.UnfairExecutor$Worker.run(UnfairExecutor.java:407), java.base/java.lang.Thread.run(Thread.java:853)]`

**Comment by frqnny** [comment]
who cares tho? I know its there, idrc wontfix
