### ISSUE TITLE
Add Pillager Factory Maps

### ISSUE THREAD

**Issue by beautiful-lunatic** [frqnny/mostructures#45]
I noticed there is a chest outside of the pillager factory that has a sign on it, saying "TO WOODLAND MANSION", but when I open the chest, there is no map. I don't know if there is supposed to be a map, but I would have thought so since the sign says "to woodland mansion". Other than that, awesome mod! Looking forward to future updates and builds!

**Comment by frqnny** [comment]
OOOOOOOHH I COULD DO A MAP IN THERE YEAHHHH I'D HAVE TO SEE HOW IT WORKS AND KEEP SERVER COMPAT THO SO WHO KNOWS

**Comment by beautiful-lunatic** [comment]
> OOOOOOOHH I COULD DO A MAP IN THERE YEAHHHH I'D HAVE TO SEE HOW IT WORKS AND KEEP SERVER COMPAT THO SO WHO KNOWS

Ohh so there never was supposed to be a map in there? Either way, that would be cool if there was! (depending if its hard to add one in there, I know nothing about mc modding lol)
