### ISSUE TITLE
Most structures (Fabric) advancements not displaying correctly

### ISSUE THREAD

**Issue by NOOTLORD** [frqnny/mostructures#46]
When i come across any of the mo structure buildings the advancements messages appear wrong.
Is this a known issue? I can't seem to find anobody talking out it :p 
https://imgur.com/a/fVdKIxk

**Comment by frqnny** [comment]
Update the mod server sided

**Comment by NOOTLORD** [comment]
ah i prop know why then as i only have it on the server because its only world gen so it should not require any client features but the advancements need to be present on the client aswell i assume atleast. I will add the mod to the client aswell and check if that fixes it.

**Comment by frqnny** [comment]
no update the mod its fixed
