### ISSUE TITLE
Pirate ship spawns on land

### ISSUE THREAD

**Issue by PuppetMasterZee** [frqnny/mostructures#47]
Pirate ship spawn at least partially on land creating rectangle area carved out around it. (server)

Mod version::  mostructures-1.2.0-1.16.5
Fabric api 0.36.0+1.16
Minecraft version: 1.16.5

![Pirate Ship Spawn on Land](https://user-images.githubusercontent.com/84147261/125643744-87abb1e2-46e7-4709-96f8-b1f27e67cc32.png)

**Comment by frqnny** [comment]
They generate in deep oceans. This is a very very rare occurance and basically will happen in under 1% of all cases. I can't help much with this awkard generation.

**Comment by PuppetMasterZee** [comment]
Thank you, we appreciate the response.

**Comment by frqnny** [comment]
Yep! If you have any big issues I will look into trying to figure out a mechanism for these edge cases since this is really rare. I've come across it once before, but that's it.
