### ISSUE TITLE
Crash when loading in a specific chunk

### ISSUE THREAD

**Issue by InteJason** [frqnny/mostructures#51]
The crash report mentions Mostructures: https://paste.gg/p/anonymous/82d57dece35f46829e61484090476062/files/2a63ca2b6063497fb838dbc0b6baba7e/raw

Version: 1.7.1 Fabric 0.11.6
mostructures-1.3.0-pre1-1.17.1-fabric.jar

**Comment by frqnny** [comment]
Can you give the the log text instead? this doesn't tell me much

**Comment by frqnny** [comment]
No log provided, goodbye.
