### ISSUE TITLE
Pillagers Not Spawning in Pillager Factory (Forge Version)

### ISSUE THREAD

**Issue by TheEndorVeteran** [frqnny/mostructures#55]
Hello! The Pillager Factory seems to no spawn any Pillagers on the Forge version. Ravagers spawn, and so do villagers in cages. I tried this on new worlds, and re-installing the mod. Does this mod have to be only used by itself?

**Comment by frqnny** [comment]
forge 1.16 is no longer supported. work is going to a 1.17 version.
