### ISSUE TITLE
Unintended structure spawning repeatedly in the End dimension

### ISSUE THREAD

**Issue by megatrook** [frqnny/mostructures#62]
In the void around the End island, there is a structure spawning many times repeatedly, composed of cobblestone, some gravel, a magma block, and some water. It has a shape simillar to a diamond.

To reproduce it, make a new world with Mo' Structures installed, and go to the End. Hope this bug can be fixed!

**Comment by magistermaks** [comment]
can confirm, a temporary work around would be to disable the volcanic vent structure in the config:
```json5
"volcanic_vent": {
      "activated": false,
      ...
}
```

**Comment by mbrozzo** [comment]
This also happens in the Aether and Eden Ring dimensions from the "Paradise Lost - the Aether Reborn" and "Eden Ring" mods

**Comment by frqnny** [comment]
Duplicate
