### ISSUE TITLE
A semi-active fork + not working on 1.18.2

### ISSUE THREAD

**Issue by litoj** [frqnny/mostructures#63]
Hello, it seems this repo has gone somewhat inactive, [this fork](https://github.com/filips123/mostructures) looks a little more recent. But I have no way of testing.

1.18.2 has changed api for access to worldgen to make things easier. This unfortunately came with a breaking change, so this mod is no longer working.

**Comment by JustFoxx** [comment]
So we could wait for port for fabric 1.18.2

**Comment by frqnny** [comment]
I plan on "fixing" stuff this friday

**Comment by frqnny** [comment]
I wil be able to release a 1.3.0 release update to 1.17 and 1.18 hopefully this week, check projects

**Comment by frqnny** [comment]
I released 1.3.0 to 1.17, 1.18.1 and 1.18.2 updates are coming in the next 24 hours hopefully.

**Comment by frqnny** [comment]
So, I'm going to close this issue.
