### ISSUE TITLE
Kill a Bunny and get loot advance met bug?

### ISSUE THREAD

**Issue by curiousmc** [frqnny/mostructures#67]
When I entered this specific structure, it gave me an advancement which I don't mind but it said "Mission: Kill a bunny, and get loot" I haven't even killed a bunny however I did acquired loot from a broken nether portal. Is this intended or a bug?

![image_2022-04-28_141516804](https://user-images.githubusercontent.com/104551545/165688960-87c97175-f5b8-4da9-9af4-62398d1b74ba.png)

**Comment by frqnny** [comment]
that’s your mission find the killer bunny
