### ISSUE TITLE
Too frequent

### ISSUE THREAD

**Issue by tomimissu** [frqnny/mostructures#69]
The spawning for *all structures is too much, I wonder why you didn't give the structures the same spawn chance as their *real Minecraft counterparts. Like the trading post, for example, I see it everywhere. The pillager structure as well, it can always be found a short distance from any village. I have even seen ones spawned *in a village. I do love the concept of mo'structures but if you don't start making changes, I can no longer support you.

**Comment by frqnny** [comment]
we have a config, please use it
