### ISSUE TITLE
Fix structures spawning in modded dimensions. 

### ISSUE THREAD

**Issue by Danklor** [frqnny/mostructures#7]
Some features and structures look very out of place in some modded dimensions. Adding a per-dimension allow/deny list would avoid that.

**Comment by frqnny** [comment]
they aren't supposed to spawn in modded dimensions at all... what dimension is this happening in?

**Comment by Danklor** [comment]
One dimension I remember seeing features added to was hotm:nectere biome hotm:thinking_forest. I'll keep better notes when I see it happen again.

**Comment by frqnny** [comment]
Okay, I am adding a biome blacklist. It's impossible to do a dimension check.
