### ISSUE TITLE
1.19 support

### ISSUE THREAD

**Issue by skyfallwastaken** [frqnny/mostructures#70]
Hi!
Firstly, I'd like to say that that I love the mod! I was wondering when the mod would support 1.19.
Thank you =)

**Comment by youmukonpaku1337** [comment]
mid july when frqnny returns from vacation

**Comment by youmukonpaku1337** [comment]
kinda pointless issue, it happens when it happens

**Comment by NolanHewitt** [comment]
Oof

**Comment by SafeOfArsenal** [comment]
> mid july when frqnny returns from vacation

really did a good job at making it 1.19

**Comment by frqnny** [comment]
how do I cuss out a person without breaking some BS community guidelines
