### ISSUE TITLE
Please1.19.2please!

### ISSUE THREAD

**Issue by CUX-LI** [frqnny/mostructures#72]
Please1.19.2please!

**Comment by Funtimes909** [comment]
I need as well

**Comment by Sammcb** [comment]
@frqnny Hi! Just wondering if you have any active plans to work on a 1.19 update in the next couple months? Totally fine if not, but it would be great to know if I should wait on this mod to update my modpack to 1.19. Thanks so much!

**Comment by Ayutac** [comment]
There will be no support for 1.19.2 with 99% probability

**Comment by Sammcb** [comment]
Got it, thanks for letting me know!

**Comment by 5ur3z** [comment]
+1

**Comment by allanonmage** [comment]
seems that previous similar issues have been closed with no updates.  Not sure what that means, but probably means that the dev is no longer working on this mod.

**Comment by frqnny** [comment]
lies!

**Comment by allanonmage** [comment]
Which part? I'd love to include your mod in my 1.19.2 world

**Comment by frqnny** [comment]
i'm porting it currently to 1.19.4. i know someone wants to backport it to 1.19.2 but if they don't i will when I have time. it's currently compiling but crashing on entering/creating a world (aka json issues)

**Comment by frqnny** [comment]
1.19.2 is now out, closing this issue

**Comment by Sammcb** [comment]
@frqnny thank you so much for updating the mod! Will these releases also be available through Modrinth? Thanks again!

**Comment by frqnny** [comment]
sure

**Comment by Sammcb** [comment]
Awesome, thanks so much!
