### ISSUE TITLE
Crashing

### ISSUE THREAD

**Issue by djdr1988** [frqnny/mostructures#74]
After loading a world, the game either crashes immediately, or after a few minutes, with exit code -1. Upon reviewing the crash log, this mod is listed in the first line. I am attaching the crash log.
[crash-2023-07-27_13.43.36-server.txt](https://github.com/frqnny/mostructures/files/12187256/crash-2023-07-27_13.43.36-server.txt)

**Comment by frqnny** [comment]
this was you loading the mod on a newer version when it wasn't available. closing this issue since its old.
