### ISSUE TITLE
1.20.1 support

### ISSUE THREAD

**Issue by transcental** [frqnny/mostructures#75]
Would you be able to upgrade the mod to 1.20.1 please?

**Comment by transcental** [comment]
My bad, didn't notice the 1.20 branch. Could it be published to Curseforge please?

**Comment by Mrgaton** [comment]
Yes please i need a release right nowwww aaaaaaaaaaaaaaaaaaaaaaaaaa

**Comment by frqnny** [comment]
published to curseforge and modrinth
why i didn't is beyond me, that's hundreds of dollars worth of cursepoints missed >:w
