### ISSUE TITLE
The villager_moai feature can generate in odd places.

### ISSUE THREAD

**Issue by Danklor** [frqnny/mostructures#8]
I've seen villager_moai features generate on top of vanilla sunken ships, modded vegetation, and other unlikely places. Maybe a check to make sure they are placed on sand or other reasonable blocks would be a way to fix this.

**Comment by frqnny** [comment]
haha yeah  a sand check might actually be smart... thank you

**Comment by frqnny** [comment]
Ok, going to release it in the 1.0.0 update when 1.16.2 comes out.
